version: "3.8"

services:
  web:
    build: .
    image: altravionix-react
    container_name: altravionix-react
    restart: always
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=altravionix.com,www.altravionix.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=altravionix.com,www.altravionix.com
      - LETSENCRYPT_EMAIL=ajay.baviskar88@gmail.com
